/* Auto-generated by genmsg_cpp for file /home/kelvin/wilson/roman-technologies/roman/gripper/msg/Distance.msg */
#ifndef GRIPPER_MESSAGE_DISTANCE_H
#define GRIPPER_MESSAGE_DISTANCE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace gripper
{
template <class ContainerAllocator>
struct Distance_ {
  typedef Distance_<ContainerAllocator> Type;

  Distance_()
  : distance(0)
  {
  }

  Distance_(const ContainerAllocator& _alloc)
  : distance(0)
  {
  }

  typedef int32_t _distance_type;
  int32_t distance;


private:
  static const char* __s_getDataType_() { return "gripper/Distance"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "680f8923bb6b23ec7057fffc11ea7b34"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "int32 distance\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, distance);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, distance);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(distance);
    return size;
  }

  typedef boost::shared_ptr< ::gripper::Distance_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gripper::Distance_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Distance
typedef  ::gripper::Distance_<std::allocator<void> > Distance;

typedef boost::shared_ptr< ::gripper::Distance> DistancePtr;
typedef boost::shared_ptr< ::gripper::Distance const> DistanceConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::gripper::Distance_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::gripper::Distance_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace gripper

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::gripper::Distance_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::gripper::Distance_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::gripper::Distance_<ContainerAllocator> > {
  static const char* value() 
  {
    return "680f8923bb6b23ec7057fffc11ea7b34";
  }

  static const char* value(const  ::gripper::Distance_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x680f8923bb6b23ecULL;
  static const uint64_t static_value2 = 0x7057fffc11ea7b34ULL;
};

template<class ContainerAllocator>
struct DataType< ::gripper::Distance_<ContainerAllocator> > {
  static const char* value() 
  {
    return "gripper/Distance";
  }

  static const char* value(const  ::gripper::Distance_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::gripper::Distance_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int32 distance\n\
\n\
";
  }

  static const char* value(const  ::gripper::Distance_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::gripper::Distance_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::gripper::Distance_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.distance);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Distance_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gripper::Distance_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::gripper::Distance_<ContainerAllocator> & v) 
  {
    s << indent << "distance: ";
    Printer<int32_t>::stream(s, indent + "  ", v.distance);
  }
};


} // namespace message_operations
} // namespace ros

#endif // GRIPPER_MESSAGE_DISTANCE_H

