#!/bin/bash

if [ -s /home/tux/setup.sh ]; then
    #echo "$DATE: nero-start using setup file /home/tux/setup.sh" >> $log_file
    source /home/tux/setup.sh
else
    #echo "$DATE: nero-start using setup file /opt/ros/electric/setup.bash" >> $log_file
    source /opt/ros/electric/setup.bash
fi

setuidgid tux roscore
